### ISSUE TITLE
Archiving of mails?

### ISSUE THREAD

**Issue by keirthomas** [moritzregnier/create-reminder-from-mail-mac#2]
Any chance of archiving mails after the reminder has been created for an inbox-zero approach?

**Comment by moritzregnier** [comment]
I just uploaded the feature you suggested.

**Comment by keirthomas** [comment]
Cool! Thanks! I blogged about your project here: http://www.mackungfu.org/create-email-reminders-within-email-app

**Comment by moritzregnier** [comment]
Thanks! Put your nice explanation in the readme, too.
