### ISSUE TITLE
Using latest message in grouped emails

### ISSUE THREAD

**Issue by hanpurn** [moritzregnier/create-reminder-from-mail-mac#4]
Some email of repeatedly communicat were displayed as group.
When I creat reminder from that group of emails, I want to make latest one to reminder.
But currently not latest message is going to reminder.

Sample of image below, I did email to reminder from top, but 4th message was going to remind.
<img width="400" alt="screenshot_188" src="https://cloud.githubusercontent.com/assets/15178550/13729776/c067ecd8-e95a-11e5-9766-713ee99158d8.png">

**Comment by moritzregnier** [comment]
please check if it works now for you.

**Comment by hanpurn** [comment]
Thank you for revising. It works for some case but sometimes not.
Please see two screen shot what I included in here.
But it's not major concern. I can use it with few more click.
Thanks!
<img width="398" alt="screenshot_189" src="https://cloud.githubusercontent.com/assets/15178550/13769936/0d17a568-eaa1-11e5-9372-860c670b5ec5.png">
<img width="398" alt="screenshot_190" src="https://cloud.githubusercontent.com/assets/15178550/13769937/0e23fd30-eaa1-11e5-9722-0f3eca973508.png">
